<?php

use Illuminate\Database\Seeder;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('members')->get()->count() == 0) {
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId1',
                'memberName' => '一呆',
                'memberGender' => 'memberGender1',
                'memberYear' => '1981',
                'memberMonth' => '1',
                'memberDay' => '2',
                'memberCity' => '台北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@一呆.com',
                'memberMobile' => '0911-111-111',
                'memberEmergencyContact' => '一呆緊急',
                'memberEmergencyRelationship' => '一呆關係',
                'memberEmergencyMobile' => '0922-222-222',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId2',
                'memberName' => '二呆',
                'memberGender' => 'memberGender2',
                'memberYear' => '1982',
                'memberMonth' => '3',
                'memberDay' => '4',
                'memberCity' => '新北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@二呆.com',
                'memberMobile' => '0933-333-333',
                'memberEmergencyContact' => '二呆緊急',
                'memberEmergencyRelationship' => '二呆關係',
                'memberEmergencyMobile' => '0944-444-444',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId3',
                'memberName' => '三呆',
                'memberGender' => 'memberGender3',
                'memberYear' => '1983',
                'memberMonth' => '5',
                'memberDay' => '6',
                'memberCity' => '基隆市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@三呆.com',
                'memberMobile' => '0955-555-555',
                'memberEmergencyContact' => '三呆緊急',
                'memberEmergencyRelationship' => '三呆關係',
                'memberEmergencyMobile' => '0966-666-666',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId4',
                'memberName' => '四呆',
                'memberGender' => 'memberGender4',
                'memberYear' => '1984',
                'memberMonth' => '7',
                'memberDay' => '8',
                'memberCity' => '桃園市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@四呆.com',
                'memberMobile' => '0977-777-777',
                'memberEmergencyContact' => '四呆緊急',
                'memberEmergencyRelationship' => '四呆關係',
                'memberEmergencyMobile' => '0988-888-888',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId5',
                'memberName' => '五呆',
                'memberGender' => 'memberGender5',
                'memberYear' => '1985',
                'memberMonth' => '9',
                'memberDay' => '10',
                'memberCity' => '新竹市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@五呆.com',
                'memberMobile' => '0999-999-999',
                'memberEmergencyContact' => '五呆緊急',
                'memberEmergencyRelationship' => '五呆關係',
                'memberEmergencyMobile' => '0900-000-000',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId6',
                'memberName' => '六呆',
                'memberGender' => 'memberGender6',
                'memberYear' => '1986',
                'memberMonth' => '11',
                'memberDay' => '12',
                'memberCity' => '苗栗縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@六呆.com',
                'memberMobile' => '0910-123-456',
                'memberEmergencyContact' => '六呆緊急',
                'memberEmergencyRelationship' => '六呆關係',
                'memberEmergencyMobile' => '0920-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId7',
                'memberName' => '七呆',
                'memberGender' => 'memberGender7',
                'memberYear' => '1987',
                'memberMonth' => '1',
                'memberDay' => '3',
                'memberCity' => '台中市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@七呆.com',
                'memberMobile' => '0930-123-456',
                'memberEmergencyContact' => '七呆緊急',
                'memberEmergencyRelationship' => '七呆關係',
                'memberEmergencyMobile' => '0940-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId8',
                'memberName' => '八呆',
                'memberGender' => 'memberGender8',
                'memberYear' => '1988',
                'memberMonth' => '5',
                'memberDay' => '7',
                'memberCity' => '彰化縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@八呆.com',
                'memberMobile' => '0950-123-456',
                'memberEmergencyContact' => '八呆緊急',
                'memberEmergencyRelationship' => '八呆關係',
                'memberEmergencyMobile' => '0960-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId9',
                'memberName' => '九呆',
                'memberGender' => 'memberGender9',
                'memberYear' => '1989',
                'memberMonth' => '9',
                'memberDay' => '11',
                'memberCity' => '南投縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@九呆.com',
                'memberMobile' => '0970-123-456',
                'memberEmergencyContact' => '九呆緊急',
                'memberEmergencyRelationship' => '九呆關係',
                'memberEmergencyMobile' => '0980-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId10',
                'memberName' => '十呆',
                'memberGender' => 'memberGender10',
                'memberYear' => '1989',
                'memberMonth' => '9',
                'memberDay' => '11',
                'memberCity' => '南投縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十呆.com',
                'memberMobile' => '0970-123-456',
                'memberEmergencyContact' => '十呆緊急',
                'memberEmergencyRelationship' => '十呆關係',
                'memberEmergencyMobile' => '0980-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId11',
                'memberName' => '十一呆',
                'memberGender' => 'memberGender11',
                'memberYear' => '1981',
                'memberMonth' => '1',
                'memberDay' => '2',
                'memberCity' => '台北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十一呆.com',
                'memberMobile' => '0911-111-111',
                'memberEmergencyContact' => '十一呆緊急',
                'memberEmergencyRelationship' => '十一呆關係',
                'memberEmergencyMobile' => '0922-222-222',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId12',
                'memberName' => '十二呆',
                'memberGender' => 'memberGender12',
                'memberYear' => '1982',
                'memberMonth' => '3',
                'memberDay' => '4',
                'memberCity' => '新北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十二呆.com',
                'memberMobile' => '0933-333-333',
                'memberEmergencyContact' => '十二呆緊急',
                'memberEmergencyRelationship' => '十二呆關係',
                'memberEmergencyMobile' => '0944-444-444',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId13',
                'memberName' => '十三呆',
                'memberGender' => 'memberGender13',
                'memberYear' => '1983',
                'memberMonth' => '5',
                'memberDay' => '6',
                'memberCity' => '基隆市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十三呆.com',
                'memberMobile' => '0955-555-555',
                'memberEmergencyContact' => '十三呆緊急',
                'memberEmergencyRelationship' => '十三呆關係',
                'memberEmergencyMobile' => '0966-666-666',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId14',
                'memberName' => '十四呆',
                'memberGender' => 'memberGender14',
                'memberYear' => '1984',
                'memberMonth' => '7',
                'memberDay' => '8',
                'memberCity' => '桃園市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十四呆.com',
                'memberMobile' => '0977-777-777',
                'memberEmergencyContact' => '十四呆緊急',
                'memberEmergencyRelationship' => '十四呆關係',
                'memberEmergencyMobile' => '0988-888-888',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId15',
                'memberName' => '十五呆',
                'memberGender' => 'memberGender15',
                'memberYear' => '1985',
                'memberMonth' => '9',
                'memberDay' => '10',
                'memberCity' => '新竹市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十五呆.com',
                'memberMobile' => '0999-999-999',
                'memberEmergencyContact' => '十五呆緊急',
                'memberEmergencyRelationship' => '十五呆關係',
                'memberEmergencyMobile' => '0900-000-000',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId16',
                'memberName' => '十六呆',
                'memberGender' => 'memberGender16',
                'memberYear' => '1986',
                'memberMonth' => '11',
                'memberDay' => '12',
                'memberCity' => '苗栗縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十六呆.com',
                'memberMobile' => '0910-123-456',
                'memberEmergencyContact' => '十六呆緊急',
                'memberEmergencyRelationship' => '十六呆關係',
                'memberEmergencyMobile' => '0920-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId17',
                'memberName' => '十七呆',
                'memberGender' => 'memberGender17',
                'memberYear' => '1987',
                'memberMonth' => '1',
                'memberDay' => '3',
                'memberCity' => '台中市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十七呆.com',
                'memberMobile' => '0930-123-456',
                'memberEmergencyContact' => '十七呆緊急',
                'memberEmergencyRelationship' => '十七呆關係',
                'memberEmergencyMobile' => '0940-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId18',
                'memberName' => '十八呆',
                'memberGender' => 'memberGender18',
                'memberYear' => '1988',
                'memberMonth' => '5',
                'memberDay' => '7',
                'memberCity' => '彰化縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十八呆.com',
                'memberMobile' => '0950-123-456',
                'memberEmergencyContact' => '十八呆緊急',
                'memberEmergencyRelationship' => '十八呆關係',
                'memberEmergencyMobile' => '0960-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId19',
                'memberName' => '十九呆',
                'memberGender' => 'memberGender19',
                'memberYear' => '1989',
                'memberMonth' => '9',
                'memberDay' => '11',
                'memberCity' => '南投縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@十九呆.com',
                'memberMobile' => '0970-123-456',
                'memberEmergencyContact' => '十九呆緊急',
                'memberEmergencyRelationship' => '十九呆關係',
                'memberEmergencyMobile' => '0980-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId20',
                'memberName' => '二十呆',
                'memberGender' => 'memberGender20',
                'memberYear' => '1989',
                'memberMonth' => '9',
                'memberDay' => '11',
                'memberCity' => '南投縣',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@二十呆.com',
                'memberMobile' => '0970-123-456',
                'memberEmergencyContact' => '二十呆緊急',
                'memberEmergencyRelationship' => '二十呆關係',
                'memberEmergencyMobile' => '0980-123-456',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId21',
                'memberName' => '二一呆',
                'memberGender' => 'memberGender21',
                'memberYear' => '1981',
                'memberMonth' => '1',
                'memberDay' => '2',
                'memberCity' => '台北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@二一呆.com',
                'memberMobile' => '0911-111-111',
                'memberEmergencyContact' => '十二一呆緊急',
                'memberEmergencyRelationship' => '二一呆關係',
                'memberEmergencyMobile' => '0922-222-222',
            ]);
            DB::table('members')->insert([
                'memberTwId' => 'memberTwId22',
                'memberName' => '二二呆',
                'memberGender' => 'memberGender22',
                'memberYear' => '1982',
                'memberMonth' => '3',
                'memberDay' => '4',
                'memberCity' => '新北市',
                'memberTown' => '天下區',
                'memberAddr' => '市府路',
                'memberEmail' => 'email@二二呆.com',
                'memberMobile' => '0933-333-333',
                'memberEmergencyContact' => '二二呆緊急',
                'memberEmergencyRelationship' => '二二呆關係',
                'memberEmergencyMobile' => '0944-444-444',
            ]);
        }
    }
}
